"use strict";
let admin;

function getAdmin() {
  if (admin) return admin;
  admin = require("firebase-admin");

  if (!admin.apps.length) {
    const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT || "{}");
    admin.initializeApp({
      credential: admin.credential.cert(serviceAccount),
      projectId:  serviceAccount.project_id,
    });
  }
  return admin;
}

/**
 * Crée ou met à jour les paramètres Firebase Remote Config pour une app.
 * @param {string} packageId
 * @param {object} params  — { key: defaultValue, ... }
 */
async function setupRemoteConfig(packageId, params) {
  const a  = getAdmin();
  const rc = a.remoteConfig();

  // Récupère le template existant (ou crée un nouveau)
  let template;
  try {
    template = await rc.getTemplate();
  } catch {
    template = rc.createTemplateFromJSON(JSON.stringify({ parameters: {}, conditions: [], version: {} }));
  }

  // Ajoute / met à jour chaque paramètre
  for (const [key, value] of Object.entries(params)) {
    template.parameters[key] = {
      defaultValue:  { value: String(value) },
      displayName:   key.replace(/_/g, " "),
      valueType:     typeof value === "boolean" ? "BOOLEAN" : "STRING",
      description:   `Auto-generated by App Factory for ${packageId}`,
    };
  }

  await rc.publishTemplate(template);
  return { success: true, parametersSet: Object.keys(params) };
}

module.exports = { setupRemoteConfig };
